# Generated by Django 6.0.8 on 2026-10-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=64)),
                ('rid', models.CharField(max_length=64)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('entity', 'rid'), name='unique_entity_rid')],
            },
        ),
    ]
